image: "python:3.8-buster"

cache:
  paths:
    - apt-cache
  key: ${CI_COMMIT_REF_SLUG}

variables:
  PIPELINES_URL: "https://gitlab.aai.lab/resources/template_tests/python_library_template_output/-/pipelines"

integration_test:
  stage: test
  script:
    - mkdir -p apt-cache
  # pandoc needed for docu, see https://nbsphinx.readthedocs.io/en/0.7.1/installation.html?highlight=pandoc#pandoc
    - apt-get update -yq && apt-get -o dir::cache::archives="$(pwd)/apt-cache" install -yq pandoc
    - pip install cookiecutter tox
    - git config --global user.email automated@gitlab.com
    - git config --global user.name "automated_user"
    - chmod +x tests/integration_test.sh
    - tests/integration_test.sh
    - |
      echo Pushing to template_output remote
      chmod 0600 $GITLAB_DEPLOY_KEY

      # HTTPS clone URL -> git+ssh URL for pushing
      export GIT_SSH_COMMAND='ssh -i $GITLAB_DEPLOY_KEY -o IdentitiesOnly=yes -o StrictHostKeyChecking=no'

      cd ../python_library_template_output
      git push -f
    - echo "visit the UI to see if the generated project's pipeline is successful \n{$PIPELINES_URL}"
