image: "python:3.7-stretch"

tox:
  stage: "test"
  script:
    - pip install tox
    - tox

package:
  stage: "package"
  script:
    - pip install setuptools wheel
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/*.whl


