image: "python:{{cookiecutter.python_version}}-buster"

stages:
  - tox
  - publish

 tox:
  stage: tox
  script:
    - pip install tox
    - tox
  artifacts:
    paths:
      - badges
      - docs/_build
      - htmlcov
      - pylint.html

package:
  stage: publish
  script:
    - pip install setuptools wheel
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/*.whl

pages:
  stage: publish
  dependencies:
    - tox
  script:
    - mv docs/_build/html/* public/docs
    - mv pylint.html public/pylint/index.html
    - mv htmlcov/* public/coverage
  artifacts:
    paths:
    - public
  only:
    - develop
