default_install_hook_types: [commit-msg, pre-commit]
default_stages: [commit, manual]
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: poetry run ruff
        require_serial: true
        language: system
        types: [python]
      - id: ruff-nb
        name: ruff-nb
        entry: poetry run nbqa ruff .
        require_serial: true
        language: system
        pass_filenames: false
        types: [python]
      - id: black
        name: black
        entry: poetry run black
        require_serial: true
        language: system
        types: [python]
      - id: poetry-check
        name: poetry check
        entry: poetry check
        language: system
        files: pyproject.toml
        pass_filenames: false
      - id: poetry-lock-check
        name: poetry lock check
        entry: poetry check
        args: [--lock]
        language: system
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: poetry run mypy src
        # filenames should not be passed as they would collide with the config in pyproject.toml
        pass_filenames: false
        files: '^src(/[^/]*)*/[^/]*\.py$'
        language: system
      - id: mypy-nb
        name: mypy-nb
        entry: poetry run nbqa mypy
        language: system
