# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  fail_on_warning: true
  configuration: docs/conf.py

python:
  version: {{cookiecutter.python_version}}
  install:
    - requirements: docs/requirements.txt
