# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - curl -sSL https://install.python-poetry.org | python -
#    - ~/.local/bin/poetry config virtualenvs.create false
    - ~/.local/bin/poetry install --with dev
##   Same as poe tasks, but unfortunately poe doesn't work with poetry not creating virtualenvs
    - ~/.local/bin/poetry run python docs/autogen_rst.py
    - ~/.local/bin/poetry run which jupyter-book
    - ~/.local/bin/poetry run python docs/create_toc.py
    - ~/.local/bin/poetry run jupyter-book config sphinx docs/
    - ~/.local/bin/poetry run sphinx-build -W -b html docs $READTHEDOCS_OUTPUT/html
