# Core dependencies
[dependencies]
{% if cookiecutter.include_accsr_configuration_utils == "y" %}
accsr = "0.4.6"
{% endif %}
pandas = "2.2.1"
plotly = "5.19.0"

# Development dependencies
[dev-dependencies]
black = {version = "23.7.0", extras = ["jupyter"]}
docutils = "0.20.1"
jinja2 = "*"
jupyter = "1.0.0"
jupyter-book = "1.0.0"
mypy = "1.4.1"
nbqa = "1.7.1"
nbstripout = "0.6.1"
poethepoet = "0.20.0"
pre-commit = "3.3.3"
pytest = "8.0.2"
pytest-cov = "*"
pytest-lazy-fixtures = "1.0.5"
ruff = "0.0.285"
sphinx = "7"
sphinx-book-theme = "1.0.1"
sphinx-comments = "0.0.3"
sphinx-copybutton = "0.5.2"
sphinx-jupyterbook-latex = "1.0.0"
sphinx-togglebutton = "0.3.2"
sphinx-toolbox = "3.5.0"
sphinxcontrib-bibtex = "*"
sphinxcontrib-spelling = "8.0.0" 
toml-sort = "0.24.2"
