[project]
name = "{{cookiecutter.project_name}}"
version = "{{cookiecutter.initial_version}}"
description = ""
authors = ["{{cookiecutter.author}} <{{cookiecutter.author_email}}>"]
license = "MIT"
readme = "README.md"
python_version = "3.11"
homepage = "{{cookiecutter.project_url}}"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11",
]
package_dir = { include = "{{cookiecutter.package_name}}", from = "src" }
exclude = ["test/*", "examples/*", "docs/*"] 