name: Tests on Ubuntu

on: [push, pull_request]

jobs:
  cpu:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        python-version: ["{{cookiecutter.python_version}}"]
    {% raw -%}
    steps:
      - name: Cancel previous run
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
    {%- endraw %}

      # Include the appropriate package manager steps based on the selection
      {% if cookiecutter.package_manager == "poetry" %}
      - name: Setup and install dependencies with Poetry
        uses: ./.github/workflows/common_steps.yml
        with:
          steps: poetry-setup
      {% raw -%}
      - name: Test with pytest
        run: poetry run poe test
      {%- endraw %}
      {% elif cookiecutter.package_manager == "uv" %}
      - name: Setup and install dependencies with UV
        uses: ./.github/workflows/common_steps.yml
        with:
          steps: uv-setup
      {% raw -%}
      - name: Test with pytest
        run: uv run poe test
      {%- endraw %}
      {% elif cookiecutter.package_manager == "pixi" %}
      - name: Setup and install dependencies with Pixi
        uses: ./.github/workflows/common_steps.yml
        with:
          steps: pixi-setup
      {% raw -%}
      - name: Test with pytest
        run: pixi run poe test
      {%- endraw %}
      {% endif %}

      {% raw -%}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
      {%- endraw %}
