name: Merge master, run tests and build docu

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Merge master into current branch
        run: |
          git fetch origin master:master --update-head-ok
          git merge master
      - name: Setup Python {{cookiecutter.python_version}}
        uses: actions/setup-python@v1
        with:
          python-version: {{cookiecutter.python_version}}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox -e py -e docs # Run tox using the version of Python in `PATH`
      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: "3.6"
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox -e py  # Run tox using the version of Python in `PATH`, don't build docs on py36 due to bugs in sphinx
