name: Merge develop, run tests and build documentation

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop, master]
  workflow_dispatch:
    inputs:
      reason:
        description: Why did you trigger the pipeline?
        required: False
        default: Check if it runs again due to external changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # pandoc needed for docu, see https://nbsphinx.readthedocs.io/en/0.7.1/installation.html?highlight=pandoc#pandoc
      - name: Install Non-Python Packages
        run: sudo apt-get update -yq && sudo apt-get -yq install pandoc
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
          lfs: true
          persist-credentials: false
      # lfs=true is not enough, see https://stackoverflow.com/questions/61463578/github-actions-actions-checkoutv2-lfs-true-flag-not-converting-pointers-to-act
      - name: Checkout LFS Objects
        run: git lfs pull
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Merge develop into current branch
        if: github.ref != 'refs/heads/develop'
        run: |
          git fetch origin develop:develop --update-head-ok
          git merge develop
      - name: Setup Python {{cookiecutter.python_version}}
        uses: actions/setup-python@v1
        with:
          python-version: {{cookiecutter.python_version}}
